/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Ob7kalkVkeb
 */

import { Link } from 'react-router-dom';

function NotFound() {
  return (
    <div>
      <div className="flex items-center justify-center w-full min-h-[50vh] flex-col gap-2 p-4 text-center">
        <div className="space-y-2 text-center">
          <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl">
            404 Not Found
          </h1>
          <p className="text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            The page you were looking for could not be found.
          </p>
        </div>
        <Link
          className="inline-flex h-10 items-center rounded-md border  border-gray-200 bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50  dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300"
          to="/"
        >
          Go back
        </Link>
      </div>
    </div>
  );
}

export default NotFound;
