/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Rf3UczycMGu
 */
import { Button } from '@/components/ui/button';
import agent from '@/server/api';
import { useState } from 'react';

export function ButtonGroup() {
  const [validationError, setvalidationError] = useState<string[]>([]);
  function getValidationError() {
    agent.TestErrors.getValidationError()
      .then(() => console.log('cant see me'))
      .catch((error) => setvalidationError(error));
  }
  return (
    <div>
      <div className="flex items-center justify-center space-x-4 mt-8">
        <Button onClick={() => agent.TestErrors.get400Error()}>
          400 BAD ERROR
        </Button>

        <Button onClick={() => agent.TestErrors.get401Error()}>
          401 Unauthoized
        </Button>

        <Button onClick={() => agent.TestErrors.get404Error}>
          404 Not Found
        </Button>

        <Button onClick={() => agent.TestErrors.get500Error()}>
          500 Error
        </Button>

        <Button onClick={getValidationError}>Validation Error</Button>
      </div>
      <div>
        {validationError.map((x) => (
          <div key={x}>{x}</div>
        ))}
      </div>
    </div>
  );
}

export default ButtonGroup;
