import Hero from '@/components/component/Hero';
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/No3etoKRENv
 */

import { useQuery } from '@tanstack/react-query';
import { ApiError, Product, getProducts } from '@/server/products-data';

export function Homepage() {
  const { data, error } = useQuery<Product[], ApiError>({
    queryKey: ['products'],
    queryFn: getProducts,
  });
  if (data) {
    return (
      <div className="flex flex-col min-h-[100dvh]">
        <main className="flex-1 mt-4">
          <Hero />
        </main>
        <div className="grid grid-cols-4">
          {data.map((x: any) => (
            <div>{x.name}</div>
          ))}
        </div>
      </div>
    );
  }
  if (error) {
    return 'An error has occurred: ' + error.message;
  }
  return 'loading....';
}
